name: Terraform Apply

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tf_apply:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform fmt
        id: tf_fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Init
        id: tf_init
        run: | 
          terraform init \
          -backend-config="key=$TF_VAR_aws_backend_key" \
          -backend-config="bucket=$TF_VAR_aws_backend_bucket" \
          -backend-config="region=$TF_VAR_aws_region"
        working-directory: ./terraform
        env:
          TF_VAR_aws_backend_key: ${{vars.AWS_BACKEND_KEY}}
          TF_VAR_aws_backend_bucket: ${{ vars.AWS_BUCKET_BACKEND}}
          TF_VAR_aws_region: ${{vars.AWS_REGION}}

      - name: Terraform Validate
        id: tf_validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: tf_plan
        run: |
          terraform plan
        env:
          TF_VAR_aws_backend_key: ${{vars.AWS_BACKEND_KEY}}
          TF_VAR_aws_backend_bucket: ${{ vars.AWS_BUCKET_BACKEND}}
          TF_VAR_aws_region: ${{vars.AWS_REGION}}
          TF_VAR_main_uri: ${{ vars.MAIN_URI}}
          TF_VAR_factorio_uri: ${{vars.FACTORIO_URI}}
          TF_VAR_myip : ${{vars.MY_IP}}
        working-directory: ./terraform

      - name: Terraform Apply
        id: tf_apply
        run: |
          terraform apply -auto-approve
        env:
          TF_VAR_aws_backend_key: ${{vars.AWS_BACKEND_KEY}}
          TF_VAR_aws_backend_bucket: ${{ vars.AWS_BUCKET_BACKEND}}
          TF_VAR_aws_region: ${{vars.AWS_REGION}}
          TF_VAR_main_uri: ${{ vars.MAIN_URI}}
          TF_VAR_factorio_uri: ${{vars.FACTORIO_URI}}
          TF_VAR_myip: ${{vars.MY_IP}}
        working-directory: ./terraform